using ArchiveHashVerifier;
using System.Text;
internal static class BatchTestCases
{
 private static readonly string Root=Path.Combine(Path.GetTempPath(),"ahv-v114-"+Guid.NewGuid().ToString("N"));
 public static Task SettingsDefaultAndMigration(){Eq(true,new AppSettings().GenerateBatchOutput);string d=Dir();File.WriteAllText(Path.Combine(d,FileDiscovery.SettingsFileName),"{\"GenerateSha512\":false}");Eq(true,new SettingsService(d).Load().GenerateBatchOutput);new SettingsService(d).Save(new AppSettings{GenerateBatchOutput=false});Eq(false,new SettingsService(d).Load().GenerateBatchOutput);return Task.CompletedTask;}
 public static async Task FixedOutputsAndOrder(){string d=Dir();string z=await DataFile(d,"x.bin","z");string a=await DataFile(d,"a.bin","a");var s=await Gen([z,a],[HashKind.Sha512,HashKind.Blake3]);Eq(2,s.Ok);string sha=Path.Combine(d,"ArchiveHashVerifier.sha512");string b3=Path.Combine(d,"ArchiveHashVerifier.blake3");Ok(File.Exists(sha)&&File.Exists(b3));string text=await File.ReadAllTextAsync(sha);Ok(text.Contains("  a.bin\r\n")&&text.IndexOf("a.bin",StringComparison.Ordinal)<text.IndexOf("z.bin",StringComparison.Ordinal));Ok(!(await File.ReadAllBytesAsync(sha)).Take(3).SequenceEqual(new byte[]{239,187,191}));}
 public static async Task DifferentDirectoriesReject(){string a=await DataFile(Dir(),"a.bin","a");string b=await DataFile(Dir(),"b.bin","b");var s=await Gen([a,b],[HashKind.Sha256]);Eq(1,s.Errors);Ok(!File.Exists(Path.Combine(Path.GetDirectoryName(a)!,"ArchiveHashVerifier.sha256")));}
 public static async Task ManifestDeterministicAndSafe(){string d=Dir();var e=new[]{new BatchManifestEntry("a.bin",1,new Dictionary<HashKind,string>{{HashKind.Sha512,new string('a',128)}})};string t=BatchArtifacts.ManifestText(e);string p=Path.Combine(d,BatchArtifacts.Manifest);await File.WriteAllTextAsync(p,t,new UTF8Encoding(false));Eq(t,BatchArtifacts.ManifestText(e));Eq("a.bin",BatchArtifacts.ParseManifest(p)[0].Name);await File.WriteAllTextAsync(p,"{\"format\":\"ArchiveHashVerifier Manifest\",\"version\":1,\"files\":[{\"name\":\"..\\x\",\"size\":1,\"hashes\":{\"SHA-512\":\""+new string('a',128)+"\"}}]}");try{BatchArtifacts.ParseManifest(p);throw new Exception("traversal accepted");}catch(InvalidDataException){}catch(System.Text.Json.JsonException){}}
 public static Task ReservedExcluded(){Ok(FileDiscovery.ShouldExcludeFromGeneration("ArchiveHashVerifier.manifest"));Ok(FileDiscovery.ShouldExcludeFromGeneration("ArchiveHashVerifier.sha512"));return Task.CompletedTask;}
 public static async Task DirectBatchAndManifestVerify(){string d=Dir();string a=await DataFile(d,"a.bin","data");await Gen([a],[HashKind.Sha512,HashKind.Blake3]);var c=new ProcessingCoordinator(new GpgService("Z:\\missing\\gpg.exe"));Eq(2,(await c.VerifyAsync([Path.Combine(d,"ArchiveHashVerifier.sha512"),Path.Combine(d,"ArchiveHashVerifier.blake3")],null,null,CancellationToken.None)).Ok);Eq(2,(await c.VerifyAsync([a],null,null,CancellationToken.None)).Ok);var h=(await System.Security.Cryptography.SHA512.HashDataAsync(File.OpenRead(a))).AsSpan();var e=new[]{new BatchManifestEntry("a.bin",4,new Dictionary<HashKind,string>{{HashKind.Sha512,Convert.ToHexString(h).ToLowerInvariant()}})};await File.WriteAllTextAsync(Path.Combine(d,BatchArtifacts.Manifest),BatchArtifacts.ManifestText(e),new UTF8Encoding(false));var r=await c.VerifyAsync([Path.Combine(d,BatchArtifacts.Manifest)],null,null,CancellationToken.None);Eq(1,r.Ok);}
 public static Task TransactionRollback(){string d=Dir();string a=Path.Combine(d,"a"),b=Path.Combine(d,"b"),ta=Path.Combine(d,"ta"),tb=Path.Combine(d,"tb");File.WriteAllText(a,"old-a");File.WriteAllText(b,"old-b");File.WriteAllText(ta,"new-a");File.WriteAllText(tb,"new-b");BatchTransaction.FaultInjector=(_,n,_)=>n==4?new IOException("injected"):null;try{try{BatchTransaction.Commit([(ta,a),(tb,b)]);throw new Exception("failure missing");}catch(IOException){}Eq("old-a",File.ReadAllText(a));Eq("old-b",File.ReadAllText(b));}finally{BatchTransaction.FaultInjector=null;}return Task.CompletedTask;}
 public static Task TransactionFailureMatrix(){string d=Dir();string a=Path.Combine(d,"a"),b=Path.Combine(d,"b"),ta=Path.Combine(d,"ta"),tb=Path.Combine(d,"tb");void Prepare(bool oldA,bool oldB){foreach(string p in new[]{a,b,ta,tb})if(File.Exists(p))File.Delete(p);if(oldA)File.WriteAllText(a,"old-a");if(oldB)File.WriteAllText(b,"old-b");File.WriteAllText(ta,"new-a");File.WriteAllText(tb,"new-b");}try{Prepare(true,true);BatchTransaction.FaultInjector=(s,_,_)=>s=="backup"?new IOException("backup"):null;Throws(()=>BatchTransaction.Commit([(ta,a),(tb,b)]));Eq("old-a",File.ReadAllText(a));Eq("old-b",File.ReadAllText(b));Prepare(true,false);BatchTransaction.FaultInjector=(s,n,_)=>s=="commit"&&n==2?new IOException("commit"):null;Throws(()=>BatchTransaction.Commit([(ta,a),(tb,b)]));Eq("old-a",File.ReadAllText(a));Ok(!File.Exists(b));Prepare(true,true);BatchTransaction.FaultInjector=(s,_,_)=>s=="cleanup"?new IOException("cleanup"):null;var warnings=BatchTransaction.Commit([(ta,a),(tb,b)]);Eq(2,warnings.Count);Eq("new-a",File.ReadAllText(a));Eq("new-b",File.ReadAllText(b));Ok(Directory.EnumerateFiles(d,"*.ahvbak-*",SearchOption.TopDirectoryOnly).Any());Prepare(true,false);BatchTransaction.FaultInjector=(s,_,_)=>s=="commit"||s=="rollback-restore"?new IOException("rollback"):null;try{BatchTransaction.Commit([(ta,a),(tb,b)]);throw new Exception("critical failure missing");}catch(IOException ex){Ok(ex.Message.Contains("重大",StringComparison.Ordinal));}Ok(Directory.EnumerateFiles(d,"*.ahvbak-*",SearchOption.TopDirectoryOnly).Any());}finally{BatchTransaction.FaultInjector=null;}return Task.CompletedTask;}
 public static async Task BatchCancellationBeforeCommit(){string d=Dir();string a=await DataFile(d,"a.bin","payload");using var cts=new CancellationTokenSource();cts.Cancel();var result=await new ProcessingCoordinator(new GpgService("Z:\\missing\\gpg.exe")).GenerateAsync([a],new GenerationOptions{Hashes=[HashKind.Sha512],BatchOutput=true},(_,_,_)=>Task.FromResult(true),null,null,cts.Token);Ok(result.Results.Any(x=>x.State==ResultState.Cancelled));Ok(!File.Exists(Path.Combine(d,"ArchiveHashVerifier.sha512")));Ok(!Directory.EnumerateFiles(d,"*.ahvtmp-*",SearchOption.TopDirectoryOnly).Any());}
 public static async Task SpacesAndMissingEntry(){string d=Dir();string a=await DataFile(d,"My  Video.mkv","a");string b=await DataFile(d,"other.bin","b");await Gen([a],[HashKind.Sha512]);var c=new ProcessingCoordinator(new GpgService("Z:\\missing\\gpg.exe"));Eq(1,(await c.VerifyAsync([Path.Combine(d,"ArchiveHashVerifier.sha512")],null,null,CancellationToken.None)).Ok);var r=await c.VerifyAsync([b],null,null,CancellationToken.None);Eq(1,r.Errors);} private static void Throws(Action action){try{action();throw new Exception("exception missing");}catch(IOException){}} private static Task<OperationSummary> Gen(IEnumerable<string> f,IEnumerable<HashKind> k)=>new ProcessingCoordinator(new GpgService("Z:\\missing\\gpg.exe")).GenerateAsync(f.ToArray(),new GenerationOptions{Hashes=k.ToHashSet(),BatchOutput=true},(_,_,_)=>Task.FromResult(true),null,null,CancellationToken.None);
 private static string Dir(){string d=Path.Combine(Root,Guid.NewGuid().ToString("N"));Directory.CreateDirectory(d);return d;} private static async Task<string> DataFile(string d,string n,string x){string p=Path.Combine(d,n);await System.IO.File.WriteAllTextAsync(p,x);return p;} private static void Eq<T>(T e,T a){if(!EqualityComparer<T>.Default.Equals(e,a))throw new Exception($"{e}!={a}");}private static void Ok(bool x){if(!x)throw new Exception("assert");}
}







