using System.Text;
namespace ArchiveHashVerifier;
public sealed partial class ProcessingCoordinator
{
 private async Task<OperationSummary> VerifyBatchChecksumAsync(string checksum,IProgress<FileReadProgress>? progress,Action<string>? log,CancellationToken ct)
 {
  var sum=new OperationSummary();var spec=HashCatalog.All.Single(x=>BatchArtifacts.Names[x.Kind].Equals(Path.GetFileName(checksum),StringComparison.OrdinalIgnoreCase));string dir=Path.GetDirectoryName(checksum)!;var names=new HashSet<string>(StringComparer.OrdinalIgnoreCase);
  foreach(string line in File.ReadAllLines(checksum,Encoding.UTF8).Where(x=>x.Length>0)){int i=line.IndexOf("  ",StringComparison.Ordinal);if(i!=spec.HexLength){sum.Results.Add(new(checksum,spec.DisplayName,ResultState.Error,"一括Hash形式が不正です。"));continue;}string expected=line[..i],name=line[(i+2)..];if(expected.Length!=spec.HexLength||!expected.All(Uri.IsHexDigit)||!BatchArtifacts.IsSafeBasename(name)||!names.Add(name)){sum.Results.Add(new(checksum,spec.DisplayName,ResultState.Error,"一括Hash entryが不正です。"));continue;}string source=Path.GetFullPath(Path.Combine(dir,name));if(!Path.GetDirectoryName(source)!.Equals(dir,StringComparison.OrdinalIgnoreCase)||!File.Exists(source)){sum.Results.Add(new(source,spec.DisplayName,ResultState.Error,"元ファイルが見つかりません。"));continue;}SourceSnapshot before=SourceSnapshot.Capture(source);await using var stream=new FileStream(source,FileMode.Open,FileAccess.Read,FileShare.Read,1024*1024,FileOptions.Asynchronous|FileOptions.SequentialScan);var actual=await HashService.ComputeAsync(stream,[spec.Kind],source,0,stream.Length,progress,ct);bool ok=before.Matches(source)&&actual[spec.Kind].Equals(expected,StringComparison.OrdinalIgnoreCase);sum.Results.Add(new(source,$"一括 {spec.DisplayName}",ok?ResultState.Ok:ResultState.Ng,ok?"一致":"ハッシュ不一致"));log?.Invoke($"{(ok?"OK":"NG")} [一括 {spec.DisplayName}] {source}");}return sum;
 }
 private async Task<OperationSummary> VerifyManifestAsync(string input,IProgress<FileReadProgress>? progress,Action<string>? log,CancellationToken ct,IProgress<OperationPhase>? phase,Func<Task<bool>>? confirmMissingPublicKey)
 {
  var sum=new OperationSummary();string dir=Path.GetDirectoryName(input)!;string manifest=Path.Combine(dir,BatchArtifacts.Manifest);if(!File.Exists(manifest)){sum.Results.Add(new(input,"manifest",ResultState.Error,"ArchiveHashVerifier.manifestが見つかりません。"));return sum;}byte[] manifestBytes=await File.ReadAllBytesAsync(manifest,ct);string frozen=CreateTempPath(manifest);await File.WriteAllBytesAsync(frozen,manifestBytes,ct);var sigTemps=new List<string>();try{
  string[] signs=[manifest+".asc",manifest+".sig"];var signed=new List<(string Path,GpgVerifyResult Result)>();
   foreach(string sig in signs.Where(File.Exists)){if(!gpg.IsAvailable){sum.Results.Add(new(manifest,"OpenPGP",ResultState.Error,"GPGがインストールされていません。"));return sum;}byte[] sigBytes=await File.ReadAllBytesAsync(sig,ct);string frozenSig=CreateTempPath(sig);sigTemps.Add(frozenSig);await File.WriteAllBytesAsync(frozenSig,sigBytes,ct);phase?.Report(new("OpenPGP署名検証中…"));var r=await gpg.VerifyDetachedSignatureAsync(frozenSig,frozen,ct);byte[] sigAfter=await File.ReadAllBytesAsync(sig,ct);if(!sigBytes.SequenceEqual(sigAfter))r=new(GpgVerifyState.Error,"検証中に署名ファイルが変更されました。");signed.Add((sig,r));}
   bool hard=signed.Any(x=>x.Result.State is not (GpgVerifyState.Valid or GpgVerifyState.MissingPublicKey));foreach(var x in signed){ResultState state=x.Result.State==GpgVerifyState.Valid?ResultState.Ok:x.Result.State==GpgVerifyState.MissingPublicKey?ResultState.Skipped:x.Result.State==GpgVerifyState.Invalid?ResultState.Ng:ResultState.Error;sum.Results.Add(new(manifest,"OpenPGP "+Path.GetExtension(x.Path),state,x.Result.State==GpgVerifyState.MissingPublicKey?"OpenPGP署名未検証":x.Result.Message,x.Result.SignerUid,x.Result.SigningFingerprint));}
   if(hard)return sum; if(signed.Any(x=>x.Result.State==GpgVerifyState.MissingPublicKey)){if(confirmMissingPublicKey is null||!await confirmMissingPublicKey()){sum.Results.Add(new(manifest,"OpenPGP",ResultState.Cancelled,"公開鍵が無いためハッシュ検証を中止しました。"));return sum;}sum.Results.Add(new(manifest,"OpenPGP",ResultState.Skipped,"OpenPGP署名未検証 / ハッシュのみ検証"));}  IReadOnlyList<BatchManifestEntry> entries;try{entries=BatchArtifacts.ParseManifest(frozen);}catch(Exception ex){sum.Results.Add(new(manifest,"manifest",ResultState.Error,ex.Message));return sum;}if(!signs.Any(File.Exists))sum.Results.Add(new(manifest,"OpenPGP",ResultState.Skipped,"OpenPGP署名なし / ハッシュのみ検証"));
  foreach(var e in entries){string source=Path.GetFullPath(Path.Combine(dir,e.Name));if(!Path.GetDirectoryName(source)!.Equals(dir,StringComparison.OrdinalIgnoreCase)||!File.Exists(source)){sum.Results.Add(new(source,"manifest",ResultState.Error,"元ファイルが見つかりません。"));continue;}if(new FileInfo(source).Length!=e.Size){sum.Results.Add(new(source,"manifest",ResultState.Ng,"サイズ不一致"));continue;}SourceSnapshot before=SourceSnapshot.Capture(source);await using var stream=new FileStream(source,FileMode.Open,FileAccess.Read,FileShare.Read,1024*1024,FileOptions.Asynchronous|FileOptions.SequentialScan);var actual=await HashService.ComputeAsync(stream,e.Hashes.Keys.ToArray(),source,0,stream.Length,progress,ct);bool ok=before.Matches(source)&&e.Hashes.All(x=>actual[x.Key].Equals(x.Value,StringComparison.OrdinalIgnoreCase));sum.Results.Add(new(source,"manifest",ok?ResultState.Ok:ResultState.Ng,ok?"一致":"ハッシュ不一致"));log?.Invoke($"{(ok?"OK":"NG")} [manifest] {source}");}byte[] manifestAfter=await File.ReadAllBytesAsync(manifest,ct);if(!manifestBytes.SequenceEqual(manifestAfter))sum.Results.Add(new(manifest,"manifest",ResultState.Error,"検証中にmanifestが変更されました。"));return sum;}finally{foreach(string t in sigTemps)TryDelete(t);TryDelete(frozen);}
 }
}
